node:
  image: node:5.6.0
  container_name: node
  ports:
    - "8080:8080"
  volumes:
    - ./:/usr/src/app/
    - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
  entrypoint: /usr/local/bin/entrypoint.sh